# Go EZNet instance 4 configuration
# These values are passed as command-line flags in docker-compose.yml

TCP_PORT=9100
METRICS_PORT=8120
BROKER=amqp://artemis-master:61618
BROKER2=amqp://artemis-slave:61618
SELF_QUEUE=hsm-transparent-lb-inbound-go-4
OUTBOUND_QUEUE=hsm.transparent.lb.in
MAX_CONN=2000
READ_TIMEOUT=30s
LOG_FILE=/logs/go-eznet-4.log
